classdef BalatroGlobals < handle
    properties
        STATES = struct(...
            'SELECTING_HAND', 1, ...
            'HAND_PLAYED', 2, ...
            'DRAW_TO_HAND', 3, ...
            'GAME_OVER', 4, ...
            'SHOP', 5, ...
            'MENU', 11);
        
        STATE = 1;
        
        SETTINGS = struct(...
            'GAMESPEED', 1, ...
            'paused', false);
        
        C = struct(...
            'RED', [1 0 0], ...
            'BLUE', [0 0 1], ...
            'GREEN', [0 1 0], ...
            'BLACK', [0 0 0], ...
            'WHITE', [1 1 1]);
        
        handlist = {
            'Royal Flush', ...
            'Straight Flush', ...
            'Four of a Kind', ...
            'Full House', ...
            'Flush', ...
            'Straight', ...
            'Three of a Kind', ...
            'Two Pair', ...
            'Pair', ...
            'High Card'};
    end
    
    methods
        function obj = BalatroGlobals()
            obj.STATE = obj.STATES.SELECTING_HAND;
        end
    end
end